---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org1
  labels:
    app: chaincode-basic-org1
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org1
    spec:
      containers:
        - image: minhpn33/basic-cc-hlf:1.0
          imagePullPolicy: Always
          name: chaincode-basic-org1
          env:
            - name: CHAINCODE_ID
              value: "basic:2225ec3b997f822345d6c98123b5ba0dd5d5a6e8a1df337492aa776c33d54e75"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
